---
openapi: 3.0.3
info:
  title: demo
  version: 1.0.0
servers: []
paths:
  "/documents":
    get:
      summary: index
      tags:
      - Document
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - created_at
                  - updated_at
              example:
              - id: 73
                created_at: '2023-08-28T09:28:59.639Z'
                updated_at: '2023-08-28T09:28:59.639Z'
  "/documents/{id}":
    get:
      summary: show
      tags:
      - Document
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 74
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - created_at
                - updated_at
              example:
                id: 74
                created_at: '2023-08-28T09:28:59.658Z'
                updated_at: '2023-08-28T09:28:59.658Z'
